# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:

  api:
    # image: ${APP}
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 5240:5240
  web:
    # image: $APP
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 8080:80
