name: Application

on:
  workflow_call:
    inputs:
      ORGANISATION:
        required: true
        type: string
      ENVIRONMENT:
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
          required: true
      DOCKER_PASSWORD:
          required: true

jobs:

    application:
        name: 'Application'
        runs-on: ubuntu-latest
        environment:  ${{ inputs.ENVIRONMENT }}
        env:
            ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
            ORGANISATION: ${{ inputs.ORGANISATION }}
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        
        steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Install Test Requirements
          run: |
            sh ./test/requirements.sh

        - name: 'Show Variables'
          run: |
            sh ./tools_platform/environment_variables.sh
    
        - name: Docker Build
          run: |
            sh ./tools_app/docker_build.sh True True
        


  