name: 'pipeline'

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'README-TEMPLATE.md'
      - '.gitpod.yml'
      - '.cde.Dockerfile'
      - 'images/**'
      - '.github/workflows/workmanagement.yml'
      - '.github/ISSUE_TEMPLATE/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'README-TEMPLATE.md'
      - 'gitpod.yml'
      - '.cde.Dockerfile'
      - 'images/**'
      - '.github/workflows/workmanagement.yml'
      - '.github/ISSUE_TEMPLATE/**'
  workflow_dispatch:

jobs:
  application:
    uses: ./.github/workflows/application.yml
    with:
      ORGANISATION: ${{ vars.ORGANISATION }}
      ENVIRONMENT: "development"
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  development-infrastructure:
    uses: ./.github/workflows/infrastructure.yml
    needs: application
    with:
      UNIQUE_NAMESPACE: ${{ vars.UNIQUE_NAMESPACE }}
      ORGANISATION: ${{ vars.ORGANISATION }}
      ARM_REGION: ${{ vars.ARM_REGION }}
      ENVIRONMENT: "development"
    secrets:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

  production-plan-infrastructure:
    if: github.ref != 'refs/heads/main'
    uses: ./.github/workflows/infrastructure.yml
    needs: development-infrastructure
    with:
      UNIQUE_NAMESPACE: ${{ vars.UNIQUE_NAMESPACE }}
      ORGANISATION: ${{ vars.ORGANISATION }}
      ARM_REGION: ${{ vars.ARM_REGION }}
      ENVIRONMENT: "production-plan"
    secrets:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

  production-infrastructure:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/infrastructure.yml
    needs: development-infrastructure
    with:
      UNIQUE_NAMESPACE: ${{ vars.UNIQUE_NAMESPACE }}
      ORGANISATION: ${{ vars.ORGANISATION }}
      ARM_REGION: ${{ vars.ARM_REGION }}
      ENVIRONMENT: "production"
    secrets:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}